= Automotive Agile
Leonid Lezner <info@automotiveagile.org>
:toc:
:numbered:

.DRAFT
****
This document is only a rough draft.
****

[abstract]
--
Automotive Agile is a guideline for agile software development for automotive projects. Automotive Agile is based on agile principles and Automotive SPICE (ASPICE).
--

== Why: Reasons for Automotive Agile

In the last couple of years, the Manifesto for Agile Software Development became the guideline for almost all software development projects. Looking towards development for Web or mobile Applications, Backend Services (Clouds), you'll probably find no classic project management anymore. Upfront project planning simply doesn't work for software development and was abandoned for the sake of incremental-iterative work models (we simply call them today "agile").

But not in _Automotive_. Automotive (embedded) software development still clamps to the waterfall project management. The main reason to stick with waterfall processes is the believe that the software is "finished" at some point of time: Start of production (SOP). If you have some sort of car control unit, it is developed, built and delivered before the car hits production. Continuos updates and bug fixes are not possible or very expensive. You have no "DevOps" or even "Ops", the software is in field and can't be patched or fixed anymore (or only by workshop updates and car recalls).

But the world is changing, the software is getting more complex, connected and has to be updated in the field. Customers have the same expectations of the software a in a car as of their smartphone applications. And in the same time quality of the software is more important than tons of features: Apps shouldn't crash, they have to work fast and serve  customer needs. 

=== Misunderstanding of what "Agile" means in Automotive Market

Often people use the word "agile" to describe they project: Abandoning all processes, developing in a chaotic manner, almost no planning and barely documented work products. Somehow "Agile" became the opposite to "project management" and synonym for "bad quality".

Also the manifesto of agile software development is interpreted in wrong way:

> Individuals and interactions over processes and tools

Doesn't imply you can remove all processes. People, communication and collaboration are more important than defined processes. Ans maybe those people have to modify some process to work better. It means processes are not "rigid rules" and have to be pursued by "process police". And by the way: Scrum is a process and a very strict one.

> Working software over comprehensive documentation

Software quality __is__ more important that documentation. No product will be better just by having tons of requirement and architecture documents. Nevertheless having documentation helps to maintain the Software, to work with other people and to provide a documentation to users of the software. The purpose of documentation is improving the quality, not making the ASPICE assessor happy.

> Customer collaboration over contract negotiation

tbd

> Responding to change over following a plan

tbd

=== Misunderstanding what ASPICE means for development [Draft]

tbd

== How: Taking the best of both worlds [Draft]

tbd

== What: Guidelines for Automotive Agile [Draft]

=== Base process [Draft]

tbd

=== V-Model inside [Draft]

tbd

=== Lean documentation [Draft]

tbd

=== Test driven development [Draft]

tbd

=== Test as documentation [Draft]

tbd

